document.getElementById("summary-form").addEventListener("submit", function (e) {
  e.preventDefault();

  const url = document.getElementById("article-url").value;
  const loader = document.getElementById("loader");
  const summaryBox = document.getElementById("summary-box");
  const summaryContent = document.getElementById("summary-content");
  const urlDisplay = document.getElementById("url-display");
  const errorBox = document.getElementById("error-message");

  // Show loader, hide previous results and errors
  loader.classList.remove("hidden");
  summaryBox.classList.add("hidden");
  errorBox.classList.add("hidden");

  // Simulate API call with timeout
  setTimeout(() => {
    loader.classList.add("hidden");

    if (url && url.includes("http")) {
      // Show the summary box with the URL and a sample summary
      urlDisplay.textContent = new URL(url).hostname;
      summaryContent.textContent = "This is a demo summary of the article. In a real implementation, this would contain the actual summary generated by the LLaMA 3 model based on the content of the URL you provided.";
      summaryBox.classList.remove("hidden");
    } else {
      // Show error if URL is invalid
      errorBox.classList.remove("hidden");
    }
  }, 1500);
});

// Copy summary to clipboard
const copyButton = document.getElementById("copy-summary");
copyButton.addEventListener("click", () => {
  const summary = document.getElementById("summary-content").textContent;
  navigator.clipboard.writeText(summary).then(() => {
    // Show feedback
    const originalText = copyButton.innerHTML;
    copyButton.innerHTML = '<i class="fas fa-check"></i> Copied!';
    setTimeout(() => {
      copyButton.innerHTML = originalText;
    }, 2000);
  });
});

// Focus the URL input on page load
document.addEventListener("DOMContentLoaded", () => {
  document.getElementById("article-url").focus();
});
