package com.example.summitron;

import org.springframework.stereotype.Service;

@Service
public class SummarizationService {

    public String summarize(String url) {
        // In the next commit, we will replace this with a real call to the OpenAI API.
        System.out.println("Summarizing URL: " + url);
        return "This is a placeholder summary for the article at " + url + ". The real summary will be generated by OpenAI.";
    }
}
